### ISSUE TITLE
Problems after update HA 2022.11.1

### ISSUE THREAD

**Issue by dcantere** [dwainscheeren/dwains-dashboard-blueprints#103]
![Sem título](https://user-images.githubusercontent.com/109360617/200121047-91c138ec-253a-4e5d-be6e-af4980eb18de.jpg)

After upgrading HA to version 2022.11.1, I noticed that my blueprints have changed, as shown in the image. Also, you cannot install new blueprints. Did anyone manage to solve it?

**Comment by MichelJourdain** [comment]
To correct the problem you can create a theme that contains this line.  This will remove the borders.

![575F429B-EF9E-463B-B2CA-859FE1251B2B](https://user-images.githubusercontent.com/83040228/200132777-01b88ddc-6e2e-4e0d-b5cd-a40b38011e2d.jpeg)

**Comment by dcantere** [comment]
Tks!!! everything is OK
