### ISSUE TITLE
Map focus problem (Blueprints Persons)

### ISSUE THREAD

**Issue by dcantere** [dwainscheeren/dwains-dashboard-blueprints#108]
Good afternoon!!! I come again to ask for help to solve the problem of one of my page-blueprints (Persons). Whenever I click on one of the characters, its location on the map is not centered, it is right below, forcing me to drag the map to be able to center it. If you click "auto-focus" it also doesn't center the location. Does anyone have an idea how to fix this problem?
![Sem título](https://user-images.githubusercontent.com/109360617/205351278-58a604bb-efa7-43ec-9f11-9ae7dea1db54.jpg)

**Comment by MichelJourdain** [comment]
I have the same problem. Do you use Life360?

![5FC28D73-3796-4CA4-8DE0-2F298EC70BFE](https://user-images.githubusercontent.com/83040228/205703086-4a0b55fa-8e92-4845-acd2-3aa7405a7f8a.jpeg)

**Comment by dcantere** [comment]
Thanks for your help. I don't use 360. I noticed that it happened after HA updates. Before it is centered correctly.

**Comment by Medic97** [comment]
Also have this issue, what did you do to fix it?
