### ISSUE TITLE
Weather-dashboard: Navigation bar doen't work like intended

### ISSUE THREAD

**Issue by vinnie1234** [dwainscheeren/dwains-dashboard-blueprints#114]
See screenshot. Some styling doens't work 

![image](https://user-images.githubusercontent.com/10955777/213032073-a5e3ad19-bc54-4647-95ff-bf6cc38f1740.png)

**Comment by MichelJourdain** [comment]
The blueprint uses an old theme from version 2 of the dashboard.  The dwains-theme-accent no longer exists in version 3. You must change the color of the active pages.

                      styles:
                            name:
                              - color: var(--dwains-theme-accent)

**Comment by vinnie1234** [comment]
I fixed it in #119
