### ISSUE TITLE
After 2023.9 update - Custom element doesn't exist

### ISSUE THREAD

**Issue by rosicenko** [dwainscheeren/dwains-dashboard-blueprints#130]
So yesterday I updated HA core to 2023.9. And after that I have problem to load dashboard. Worst case is android app. Even after clean cache, relogin, restart I receive "Custom element doesn't exist: homepage-card." Same for devices-card, ...

If I reinstall the android app it works just for a while and breaks again.

I tried:
multiple cache cleaning
webview cache cleaning
relogin
redownloading via HACS
multiple device restarts
reinstall of the app
different devices
cloudflare cache purge

Same happens in Chrome for desktop, but here is cache purge more useful. But it also last just for a while until it stops to work again.

Any ideas what to do? Thanks in advance

**Comment by dwainscheeren** [comment]
closed?
