### ISSUE TITLE
small typo in a blueprint

### ISSUE THREAD

**Issue by Damian666** [dwainscheeren/dwains-dashboard-blueprints#53]
its really just a copy/paste thing i guess, but it looks off so :)

![msedge_2022-04-29_22-32-32](https://user-images.githubusercontent.com/2353938/166065422-d1a4d11e-49eb-4105-b3a7-8c449d50a82c.png)

i thought, I'll report it :)

https://github.com/dwainscheeren/dwains-dashboard-blueprints/tree/main/page-blueprints/systemmonitor_page#pi-hole-blueprint-home-assistant

**Comment by xBourner** [comment]
will pe fixed by pr #70
