### ISSUE TITLE
RecentlyAdded-UpcomingMedia Blueprint error

### ISSUE THREAD

**Issue by ruaandeysel** [dwainscheeren/dwains-dashboard-blueprints#57]
Hi,

Looks like there's an issue with the RecentlyAdded-UpcomingMedia blueprint.

(https://github.com/dwainscheeren/dwains-dashboard-blueprints/tree/main/card-blueprints/normal-cards/RecentlyAdded-UpcomingMedia)

When you import the blueprint it shows custom card: Horizontal Stack not installed.

Unless I'm missing something but horizontal stack is already part of HA and not custom card.

**Comment by dwainscheeren** [comment]
Try clearing your cache

**Comment by ruaandeysel** [comment]
Doesn't work. Here's screenshot.

Were did you get the custom horizontal stack card?

![Screen Shot 2022-05-04 at 9 34 42 am](https://user-images.githubusercontent.com/57021511/166590977-1aae433c-7db7-4418-a544-2c423efa2764.png)

**Comment by dwainscheeren** [comment]
What happens if you install / use it? It must work I think this is a bug of the maker.

**Comment by dayshiers** [comment]
The card will install on the page without the horizontal stack, I have just made a PR with documentation updated and removed the horizontal stack

**Comment by ruaandeysel** [comment]
Thank you for fixing
