### ISSUE TITLE
Edit titles (names) in dashboard-blueprints

### ISSUE THREAD

**Issue by dcantere** [dwainscheeren/dwains-dashboard-blueprints#95]
Hi guys, I would like to ask for your help. I imported a "Weather dashboard page Blueprint" theme to my Dashboard. All ok, but I made some name changes, however, the number of characters is greater than the original, with that, the names appear with cuts and ..., how do I make the name appear complete. What changes and where should I make them?
![Sem título](https://user-images.githubusercontent.com/109360617/185631925-c409ba49-43cc-490b-adcd-d4ea53c7f8c8.jpg)

**Comment by MichelJourdain** [comment]
You will find the "weather_dashboard_blueprint_heading" template for this page in the "config/dwains-dashboard/button_card_templates/blueprints/" directory.  You can adjust width: 90px as needed.

![E308908A-CD7F-4639-9B62-27CF1709D746](https://user-images.githubusercontent.com/83040228/185651695-bfcb5953-6d7e-4037-9533-bfb7a150c9c7.jpeg)

**Comment by dcantere** [comment]
@MichelJourdain  thank you so much!!! Everything is OK
