### ISSUE TITLE
Cannot use new blueprint

### ISSUE THREAD

**Issue by dimmuboy** [dwainscheeren/dwains-dashboard-blueprints#99]
After the latest update I can't use new installed blueprints because button **USE THIS BLUEPRINT** is missing.

![image](https://user-images.githubusercontent.com/12607479/194836994-f70c47b0-2abc-4da4-8033-ddae4b3e1805.png)

**Comment by MichelJourdain** [comment]
Page blueprints are used in a more page and Card Blueprints are used in an area.  For the people popup, you need to add the person in an area and add a popup to that person.

**Comment by dimmuboy** [comment]
You're absolutely right. Sorry, my bad
